/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MerchantsRouteImport } from './routes/merchants'
import { Route as ImportRouteImport } from './routes/import'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions.index'
import { Route as TransactionsIdRouteImport } from './routes/transactions.$id'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantsRoute = MerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TransactionsRoute,
} as any)
const TransactionsIdRoute = TransactionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TransactionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/import': typeof ImportRoute
  '/merchants': typeof MerchantsRoute
  '/reports': typeof ReportsRoute
  '/transactions': typeof TransactionsRouteWithChildren
  '/transactions/$id': typeof TransactionsIdRoute
  '/transactions/': typeof TransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/import': typeof ImportRoute
  '/merchants': typeof MerchantsRoute
  '/reports': typeof ReportsRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/transactions': typeof TransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/import': typeof ImportRoute
  '/merchants': typeof MerchantsRoute
  '/reports': typeof ReportsRoute
  '/transactions': typeof TransactionsRouteWithChildren
  '/transactions/$id': typeof TransactionsIdRoute
  '/transactions/': typeof TransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/import'
    | '/merchants'
    | '/reports'
    | '/transactions'
    | '/transactions/$id'
    | '/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/import'
    | '/merchants'
    | '/reports'
    | '/transactions/$id'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/import'
    | '/merchants'
    | '/reports'
    | '/transactions'
    | '/transactions/$id'
    | '/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  ImportRoute: typeof ImportRoute
  MerchantsRoute: typeof MerchantsRoute
  ReportsRoute: typeof ReportsRoute
  TransactionsRoute: typeof TransactionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchants': {
      id: '/merchants'
      path: '/merchants'
      fullPath: '/merchants'
      preLoaderRoute: typeof MerchantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof TransactionsRoute
    }
    '/transactions/$id': {
      id: '/transactions/$id'
      path: '/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof TransactionsIdRouteImport
      parentRoute: typeof TransactionsRoute
    }
  }
}

interface TransactionsRouteChildren {
  TransactionsIdRoute: typeof TransactionsIdRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
}

const TransactionsRouteChildren: TransactionsRouteChildren = {
  TransactionsIdRoute: TransactionsIdRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
}

const TransactionsRouteWithChildren = TransactionsRoute._addFileChildren(
  TransactionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  ImportRoute: ImportRoute,
  MerchantsRoute: MerchantsRoute,
  ReportsRoute: ReportsRoute,
  TransactionsRoute: TransactionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
